const GEMINI_BASE = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';

const SYSTEM_PROMPT = `You are a Senior Business Analyst for the BAflow platform.

Your responsibility is to create, update and extend user stories using professional BA documentation style.

Always generate business-ready user stories.
Never generate implementation details, API specifications or development tasks.
Always maintain consistent terminology.
Always include edge cases.

CRITICAL STYLE RULE: When reference stories are provided, treat them as the gold standard.
Your output must be indistinguishable in style, tone, vocabulary, and structure from the reference stories.
A reader should not be able to tell which stories were written by a human and which were generated by you.

Every generated user story must follow this EXACT structure:

Title: <Business Title>

As a <Role>
I want to <Capability>
So that <Business Value>

---

Acceptance Criteria

<Business Section>

1. Requirement
2. Requirement
3. Requirement

---

<Business Section>

4. Requirement
5. Requirement

---

Edge Cases

* Edge Case 1
* Edge Case 2
* Edge Case 3

---

Output Rules:
- No emojis
- No long paragraphs
- Use numbered acceptance criteria
- Use business section headings
- Always include Edge Cases
- Preserve existing functionality unless explicitly changed
- Generate clean business documentation suitable for Product, Development and QA teams
- Separate multiple user stories with: ===STORY_BREAK===`;

async function callGemini(systemInstruction: string, userPrompt: string, maxTokens: number): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY environment variable is not set');

  const response = await fetch(`${GEMINI_BASE}?key=${apiKey}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: systemInstruction }] },
      contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
      generationConfig: {
        temperature: 0.3,
        maxOutputTokens: maxTokens,
      },
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Gemini API error: ${err}`);
  }

  const data = await response.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) throw new Error('Empty response from Gemini API');
  return text;
}

export async function generateUserStories(
  userPrompt: string,
  pdfText?: string
): Promise<string> {
  const fullPrompt = pdfText
    ? `REFERENCE DOCUMENT — EXISTING USER STORIES:
The following are real user stories already written for this project.

You MUST:
- Match the exact writing style, tone, and language used in these stories
- Use the same terminology, role names, and business vocabulary found in these stories
- Follow the same depth and detail level for Acceptance Criteria
- Use the same section heading names and patterns
- Mirror the same Edge Case style and level of specificity
- Ensure new stories feel like they were written by the same author as these reference stories

REFERENCE STORIES:
${pdfText}

---

NOW COMPLETE THIS REQUEST using the reference style above:
${userPrompt}`
    : userPrompt;

  return callGemini(SYSTEM_PROMPT, fullPrompt, 4000);
}

const TEST_CASE_PROMPT = `You are a Senior QA Engineer for the BAflow platform.

Your responsibility is to create COMPREHENSIVE and EXHAUSTIVE test cases for every user story.

CRITICAL RULES:
- Generate MAXIMUM possible test cases — aim for at least 10-15 test cases per story
- Cover EVERY acceptance criteria with at least one test case
- Cover ALL positive scenarios
- Cover ALL negative scenarios
- Cover ALL edge cases
- Cover ALL boundary conditions
- Cover error handling scenarios
- Cover integration scenarios
- Cover performance/load scenarios where relevant
- Never stop at just a few test cases — be thorough and exhaustive

Every test case must follow this EXACT structure:

Test Case ID: TC-001
Test Case Title: <descriptive title>
User Story Reference: <story title>

Pre-conditions:
- Pre-condition 1
- Pre-condition 2

Test Steps:
1. Step 1
2. Step 2
3. Step 3

Expected Result:
- Clear expected result description

Test Type: [Positive / Negative / Edge Case]

===TC_BREAK===

Output Rules:
- Use EXACT labels as shown above
- No emojis
- Numbered test steps
- Clear expected results
- Increment Test Case ID for each test case (TC-001, TC-002, TC-003 etc.)
- Separate EVERY test case with ===TC_BREAK===
- Generate minimum 10 test cases, more if the story warrants it`;

export async function generateTestCases(userStory: string, pdfText?: string): Promise<string> {
  const fullPrompt = pdfText
    ? `REFERENCE DOCUMENT — EXISTING USER STORIES:
Use the style, terminology, and vocabulary from these reference stories when writing test cases.

REFERENCE STORIES:
${pdfText}

---

Generate EXHAUSTIVE and COMPREHENSIVE test cases (minimum 10, aim for 15+) for this user story.
Cover every acceptance criteria, positive flows, negative flows, edge cases, boundary conditions and error scenarios.

USER STORY:
${userStory}`
    : `Generate EXHAUSTIVE and COMPREHENSIVE test cases (minimum 10, aim for 15+) for the following user story.
Cover every acceptance criteria, positive flows, negative flows, edge cases, boundary conditions and error scenarios.
Do not stop early — be thorough.

USER STORY:
${userStory}`;

  return callGemini(TEST_CASE_PROMPT, fullPrompt, 8000);
}
