const OPENROUTER_BASE = 'https://openrouter.ai/api/v1';

const FREE_MODELS = [
  'openrouter/owl-alpha',
  'openai/gpt-oss-120b:free',
  'nvidia/nemotron-3-super-120b-a12b:free',
  'google/gemma-4-31b-it:free',
  'moonshotai/kimi-k2.6:free',
];

const SYSTEM_PROMPT = `You are a Senior Business Analyst for the Tuxi platform.

Your responsibility is to create, update and extend user stories using the Tuxi documentation style.

Always generate business-ready user stories.
Never generate implementation details, API specifications or development tasks.
Always maintain consistent terminology.
Always include edge cases.

CRITICAL STYLE RULE: When reference stories are provided, treat them as the gold standard. 
Your output must be indistinguishable in style, tone, vocabulary, and structure from the reference stories.
A reader should not be able to tell which stories were written by a human and which were generated by you.

Every generated user story must follow this EXACT structure:

Title: <Business Title>

As a <Role>
I want to <Capability>
So that <Business Value>

---

Acceptance Criteria

<Business Section>

1. Requirement
2. Requirement
3. Requirement

---

<Business Section>

4. Requirement
5. Requirement

---

Edge Cases

* Edge Case 1
* Edge Case 2
* Edge Case 3

---

Output Rules:
- No emojis
- No long paragraphs
- Use numbered acceptance criteria
- Use business section headings
- Always include Edge Cases
- Maintain Tuxi terminology
- Preserve existing functionality unless explicitly changed
- Generate clean business documentation suitable for Product, Development and QA teams
- Separate multiple user stories with: ===STORY_BREAK===`;

export async function generateUserStories(
  userPrompt: string,
  pdfText?: string
): Promise<string> {
  let lastError = '';

  // If PDF text was extracted, use it as a strict style and content reference
  const fullPrompt = pdfText
    ? `REFERENCE DOCUMENT — EXISTING TUXI USER STORIES:
The following are real user stories already written for this project. 

You MUST:
- Match the exact writing style, tone, and language used in these stories
- Use the same terminology, role names, and business vocabulary found in these stories
- Follow the same depth and detail level for Acceptance Criteria
- Use the same section heading names and patterns
- Mirror the same Edge Case style and level of specificity
- Ensure new stories feel like they were written by the same author as these reference stories

REFERENCE STORIES:
${pdfText}

---

NOW COMPLETE THIS REQUEST using the reference style above:
${userPrompt}`
    : userPrompt;

  for (const model of FREE_MODELS) {
    try {
      const response = await fetch(`${OPENROUTER_BASE}/chat/completions`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://tuxi-ba-assistant.vercel.app',
          'X-Title': 'Tuxi BA Assistant',
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: fullPrompt },
          ],
          temperature: 0.3,
          max_tokens: 4000,
        }),
      });

      if (!response.ok) {
        const err = await response.text();
        lastError = err;
        console.warn(`Model ${model} failed:`, err);
        continue;
      }

      const data = await response.json();
      return data.choices[0].message.content;

    } catch (err) {
      lastError = err instanceof Error ? err.message : 'Unknown error';
      console.warn(`Model ${model} threw error:`, lastError);
      continue;
    }
  }

  throw new Error(`All free models failed. Last error: ${lastError}`);
}

const TEST_CASE_PROMPT = `You are a Senior QA Engineer for the Tuxi platform.

Your responsibility is to create detailed test cases for user stories.

Every test case must follow this EXACT structure:

Test Case ID: TC-001
Test Case Title: <Title>
User Story Reference: <Story Title>

Pre-conditions:
- Pre-condition 1
- Pre-condition 2

Test Steps:
1. Step 1
2. Step 2
3. Step 3

Expected Result:
- Expected result description

Test Type: [Positive / Negative / Edge Case]

---

Output Rules:
- No emojis
- Numbered test steps
- Clear expected results
- Cover Positive, Negative, and Edge Case scenarios
- Separate multiple test cases with: ===TC_BREAK===`;

export async function generateTestCases(userStory: string, pdfText?: string): Promise<string> {
  let lastError = '';

  const fullPrompt = pdfText
    ? `REFERENCE DOCUMENT — EXISTING TUXI USER STORIES:
Use the style, terminology, and vocabulary from these reference stories when writing test cases.

REFERENCE STORIES:
${pdfText}

---

NOW GENERATE TEST CASES for this user story:
${userStory}`
    : `Generate comprehensive test cases for the following user story:\n\n${userStory}`;

  for (const model of FREE_MODELS) {
    try {
      const response = await fetch(`${OPENROUTER_BASE}/chat/completions`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
          'Content-Type': 'application/json',
          'HTTP-Referer': 'https://tuxi-ba-assistant.vercel.app',
          'X-Title': 'Tuxi BA Assistant',
        },
        body: JSON.stringify({
          model,
          messages: [
            { role: 'system', content: TEST_CASE_PROMPT },
            { role: 'user', content: fullPrompt },
          ],
          temperature: 0.3,
          max_tokens: 4000,
        }),
      });

      if (!response.ok) {
        const err = await response.text();
        lastError = err;
        continue;
      }

      const data = await response.json();
      return data.choices[0].message.content;
    } catch (err) {
      lastError = err instanceof Error ? err.message : 'Unknown error';
      continue;
    }
  }

  throw new Error(`All free models failed. Last error: ${lastError}`);
}
